return {
  'nvimdev/dashboard-nvim',
  event = 'VimEnter',
  dependencies = { { 'nvim-tree/nvim-web-devicons' } },
  config = function()
    local dashboard = require 'dashboard'

    -- Custom ASCII art header
    local header = {
      '                                                     ',
      '                                                     ',
      '                                                     ',
      '                                                     ',
      '                                                     ',
      '                                                     ',
      '                                                     ',
      '                                                     ',
      '  ███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗',
      '  ████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║',
      '  ██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║',
      '  ██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║',
      '  ██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║',
      '  ╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝',
      '                                                     ',
      "               [ Jesse's Kickstart ]                 ",
      '                                                     ',
      '                    .==.        ',
      "                   ()''()-.     ",
      '        .---.       ;--; /      ',
      "      .'_:___\". _..'.  __'.     ",
      "      |__ --==|'-''' \\'...;     ",
      '      [  ]  :[|       |---\\     ',
      "      |__| I=[|     .'    '.    ",
      "      / / ____|     :       '._ ",
      "     |-/.____.'      | :       :",
      "    /___\\ /___\\      '-'._----' ",
      '                                                     ',
      '                                                     ',
      '                                                     ',
    }

    dashboard.setup {
      theme = 'doom',
      config = {
        header = header,
        center = {
          {
            icon = '󰱼  ',
            icon_hl = 'Title',
            desc = 'Find File  ',
            desc_hl = 'String',
            key = 'sf',
            key_hl = 'Number',
            action = 'Telescope find_files',
          },
          {
            icon = '  ',
            icon_hl = 'Title',
            desc = 'Recent Files  ',
            desc_hl = 'String',
            key = 'r',
            key_hl = 'Number',
            action = 'Telescope oldfiles',
          },
          {
            icon = '  ',
            icon_hl = 'Title',
            desc = 'Find Word  ',
            desc_hl = 'String',
            key = 'g',
            key_hl = 'Number',
            action = 'Telescope live_grep',
          },
          {
            icon = '  ',
            icon_hl = 'Title',
            desc = 'Config  ',
            desc_hl = 'String',
            key = 'c',
            key_hl = 'Number',
            action = 'edit ~/.config/nvim-kickstart/init.lua',
          },
          {
            icon = '󰒲  ',
            icon_hl = 'Title',
            desc = 'Lazy  ',
            desc_hl = 'String',
            key = 'l',
            key_hl = 'Number',
            action = 'Lazy',
          },
          {
            icon = '󰈆  ',
            icon_hl = 'Title',
            desc = 'Quit  ',
            desc_hl = 'String',
            key = 'q',
            key_hl = 'Number',
            action = 'quit',
          },
        },
        footer = {
          '',
          '🚀 Ready to code - ' .. os.date '%Y-%m-%d',
        },
      },
    }
  end,
}
